# Fundamentals of PyTorch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# print(torch.__version__)

## Introduction to Tensors

<img src="https://miro.medium.com/v2/resize:fit:1008/0*zcidDaCCmJeD8y-9.png"  height="100" alt="Difference between scalar vector matrix and tensor">

Creating tensors using **torch.tensor()**

### Convention

- scalar and vector variables are written in smaller letters

- MATRIX and VECTOR variables are written in all capital letters

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Get tensor back as a Python int
scalar.item()

7

### Vector
Vector has a magnitude and direction

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

### _Dimensions_

Easy way to remember is ->
**dimension = number of square brackets**  

In [6]:
# get the dimensions of tensor
vector.ndim

1

### _Shape_

eg: [7, 7] - we have **2** x 1 elements

In [7]:
vector.shape

torch.Size([2])

### MATRIX

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

print(MATRIX.ndim)
print(MATRIX.shape)

# accessing the first row
print(MATRIX[0])

2
torch.Size([2, 2])
tensor([7, 8])


### TENSOR

In [9]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


### _Dimension of a Tensor_

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png" height=250>

In [10]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


## Random Tensors

**Why random tensors?**  
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent data

`Start with random number -> Look at Data -> Update random numbers -> Look at Data -> Update random numbers`


In [11]:
# Creating random tensor of size (3, 4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3062, 0.2306, 0.8327, 0.7223],
        [0.1846, 0.6145, 0.4829, 0.7220],
        [0.8530, 0.4859, 0.4830, 0.9159]])

In [12]:
# Creating random tensor with similar shape to Image Tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # size(height, width, color channels)

print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


In [13]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
ones.dtype

torch.float32

## Creating a Range of Tensors and Tensors-like

In [16]:
# Range of Tensors

# one_to_ten = torch.arange(0, 10)

# one_to_ten = torch.arange(start=0, end=10, step =2)\

one_to_ten = torch.arange(0, 100, 5)

one_to_ten

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [17]:
# Creating Tensors Like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes

In [18]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

print(f"Shape of the tensor is: {float_32_tensor.shape}")
print(f"Datatype of the tensor is {float_32_tensor.dtype}")
print(f"Tensor is running on the following device: {float_32_tensor.device}")


Shape of the tensor is: torch.Size([3])
Datatype of the tensor is torch.float32
Tensor is running on the following device: cpu


In [19]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Manipulating Tensors

Tensor Operations include:
- Addition
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [20]:
# ADD 10 to tensor

tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [21]:
# MULTIPLY by 10

tensor * 10

tensor([10, 20, 30])

In [22]:
# Subtract by 10

tensor - 10

tensor([-9, -8, -7])

In [23]:
# Divide by 10

tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Using In Built Functions

In [24]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [25]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication (most common neural network operation)

- Element wise multiplication
- Dot Product

### Two rules to keep in mind while performing matrix multiplication

1. **Inner Dimensions** must match
- `(3, 2) @ (3, 2)` wont work ❌
- `(2, 3) @ (3, 2)` will work ✅
- `(3, 2) @ (2, 3)` will work ✅

2. Resulting matrix has the shape of outer dimension

- `(2, 3) @ (3, 2)` => `(2, 2)`

In [26]:
 # Element wise multiplication

print(tensor, "x",  tensor)
print(f"equals: {tensor * tensor}")

tensor([1, 2, 3]) x tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [27]:
# Matrix Multiplication
%%time
print(tensor, "x",  tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3]) x tensor([1, 2, 3])
CPU times: user 3.7 ms, sys: 0 ns, total: 3.7 ms
Wall time: 12.2 ms


tensor(14)

### `Shape Errors`: One of the most common errors in Matrix Multiplication

In [28]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[2,4],
                         [6,12],
                         [8,16]])

print(tensor_A.shape, tensor_B.shape)

# Their shapes are different hence they will fail
torch.mm(tensor_A, tensor_B)

torch.Size([3, 2]) torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### `Transpose` of the matrix to fix this error

In [29]:
tensor_B.T

print(f"Transposed matrixB:")
print(f"{tensor_B.T}")

print(f"and its shape is: {tensor_B.T.shape}")

Transposed matrixB:
tensor([[ 2,  6,  8],
        [ 4, 12, 16]])
and its shape is: torch.Size([2, 3])


In [30]:
print(tensor_A)
print(tensor_B.T)

print(f"\nShapes of both matrix {tensor_A.shape} {tensor_B.T.shape}")

print("\nMatrix Multiplying these tensors: \n")
torch.matmul(tensor_A, tensor_B.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 2,  6,  8],
        [ 4, 12, 16]])

Shapes of both matrix torch.Size([3, 2]) torch.Size([2, 3])

Matrix Multiplying these tensors: 



tensor([[ 10,  30,  40],
        [ 22,  66,  88],
        [ 34, 102, 136]])

## Tensor Aggregration

- Min
- Max
- Mean
- Sum

In [50]:
# Creat a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# Find the Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [36]:
# Find the Max
torch.max(x), x.max()

(tensor(90), tensor(90))

### `DType Error`

In [41]:
# Find the mean(average)
torch.mean(x) # x has dtype int64

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [44]:
# Finding mean by changing dtype of tensor
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [45]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Positional Min, Max

- returns the index at which the min / max element is located

In [47]:
# Finding positional min

print(x)

x.argmin() # returns index of min position

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


tensor(0)

In [49]:
x.argmax() # returns index of min position

tensor(9)

## Reshaping, Stacking, Squeezing and Unsqueezing tensors

| Method |	One-line description |
| ------ | ---------------------- |
|torch.reshape(input, shape) | 	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape(). |
Tensor.view(shape) | 	Returns a view of the original tensor in a different shape but shares the same data as the original tensor. |
torch.stack(tensors, dim=0) |	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.|
torch.squeeze(input) |	Squeezes input to remove all the dimenions with value 1. |
torch.unsqueeze(input, dim) |	Returns input with a dimension value of 1 added at dim. |
torch.permute(input, dims) |	Returns a view of the original input with its dimensions permuted (rearranged) to dims. |

### Shape

In [65]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Reshape - Add extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [58]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

### `Shape Errors`

In [56]:
# Here we will get an error becuase ->
# we are trying to squeeze 9 elements into 7 elements

x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [55]:
# Here we will get an error becuase ->
# we are trying to squeeze 9 elements into 18 (9 x 2)

x_reshaped = x.reshape(2, 9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

### View

View is similar to shape, but ->  
the only difference is view **shares the same memory** as original tensor

In [66]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# changing z will change x(because their memory is shared)

print("original z and x:")
print(z, x)

z[:, 0] = 5

print("\nModifying z leads to modification of x too\n")
print("modified z and x:")
print(z, x)

original z and x:
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Modifying z leads to modification of x too

modified z and x:
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


### Stack

Stacking tensors on top of each other

In [69]:
x = torch.arange(0, 10, 2)
x

tensor([0, 2, 4, 6, 8])

In [70]:
# Stacking vertically

x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8]])

In [72]:
# Stacking horizontally

x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[0, 0, 0, 0],
        [2, 2, 2, 2],
        [4, 4, 4, 4],
        [6, 6, 6, 6],
        [8, 8, 8, 8]])

### Squeeze

Remove all single dimensions from a target tensor

In [83]:
# original tensor
x = x.reshape(1,5)
x, x.shape

(tensor([[0, 2, 4, 6, 8]]), torch.Size([1, 5]))

In [91]:
# changes dimension from (1, 5) to (5)
x.squeeze(), x.squeeze().shape

(tensor([0, 2, 4, 6, 8]), torch.Size([5]))

### Unsqueeze
add a single dimension to target tensor at specific dim

In [86]:
# original tensor
x, x.shape

(tensor([[0, 2, 4, 6, 8]]), torch.Size([1, 5]))

In [100]:
# changes dimension from (1, 5) to (1, 5, 1)
x.unsqueeze(dim=2), x.unsqueeze(dim=2).shape

(tensor([[[0],
          [2],
          [4],
          [6],
          [8]]]),
 torch.Size([1, 5, 1]))

In [93]:
# changes dimension from (1, 5) to (1, 1, 5)
x.unsqueeze(dim=0), x.unsqueeze(dim=0).shape

(tensor([[[0, 2, 4, 6, 8]]]), torch.Size([1, 1, 5]))

### Permute
Rearranges the dimensions of a target tensor in a specific order

`permute(2, 0, 1)`  
what this says is **swapping:**  
- 0th dimension to 2nd  
- 1st dimension to 0th  
- 2nd dimension to 1


In [108]:
# original image tensor
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]
x_original.shape

torch.Size([224, 224, 3])

In [109]:
# permite the original tensor
x_permutted = x_original.permute(2,0,1)
x_permutted.shape # [color_channels, height,  width]

torch.Size([3, 224, 224])

### Selecting data from tensors

In [114]:
print(x_original.shape)

torch.Size([224, 224, 3])


In [111]:
# Selecting an element
x_original[0,0,0]

tensor(0.1154)

In [112]:
## Resetting an element
x_original[0,0,0] = 0.6969
x_original[0,0,0]

tensor(0.6969)

### Indexing (selecting data from tensors)

Indexing with pyTorch is similar in indexing with numpy

In [116]:
# create a tensor
import torch

x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [118]:
 # Indexing 0th dimension

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [119]:
 # Indexing 1st dimension

x[0][1]

tensor([4, 5, 6])

In [121]:
 # Indexing 2nd dimension

x[0][1][1]

tensor(5)

In [122]:
# select all of nth dimension with ":"

x[:, 0] # select all of 0th dimension

tensor([[1, 2, 3]])

In [123]:
 # get all values of 0th and 1st dimension, but only index 1 of 2nd dimension

x[:, : , 1]

tensor([[2, 5, 8]])

In [124]:
# get all values of the 0 dimension but only 1 index value of 1st and 2nd dimension

x[:, 1, 1]

tensor([5])

In [125]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension

x[0, 0, :]

tensor([1, 2, 3])

In [126]:
# return 9
x[:,2,2]

tensor([9])

In [127]:
# return 3, 6, 9
x[:,:,2]

tensor([[3, 6, 9]])